apiVersion: v1
kind: Service
metadata:
  name: web-app-client
  namespace: web-app
spec:
  selector:
    app: web-app-client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP

