apiVersion: v1
kind: Service
metadata:
  name: web-app-server
  namespace: web-app
spec:
  selector:
    app: web-app-server
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
  type: ClusterIP

