apiVersion: v1
kind: Service
metadata:
  name: web-app-nginx
  namespace: web-app
spec:
  selector:
    app: web-app-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
